/**
 * generate-legal-seed.ts
 *
 * Reads LEGAL_REFERENCES from src/data/legal-references.ts and emits a SQL
 * migration script that seeds the public.legal_references table plus the four
 * child tables (legal_sources, legal_consequences, legal_required_documents,
 * legal_process_steps).
 *
 * Usage:
 *   npx tsx scripts/generate-legal-seed.ts > supabase/migrations/20260511000006_legal_tables_seed.sql
 *
 * Notes:
 *   - Mechanical translation: strings are copied verbatim from the TS source.
 *   - TS <-> DB field mapping:
 *       permitType        -> permit_type
 *       frequencyBasis    -> frequency_basis
 *       estimatedCost     -> estimated_cost
 *       disclaimer        -> disclaimer
 *       description       -> description
 *       sources[].shortName -> legal_sources.short_name
 *       sources[].type    -> legal_sources.type (already in snake_case enum)
 *       sources[].scope   -> legal_sources.scope (already in snake_case enum)
 *       consequences[]    -> legal_consequences.consequence
 *       requiredDocuments[] -> legal_required_documents.document
 *       typicalProcess[]  -> legal_process_steps.step
 *   - Fields not present in TS (applies_to, business_categories, government_portal_*,
 *     application_form_url, help_guide_url) are left to their column defaults
 *     (empty array / NULL).
 */

/* eslint-disable no-console -- CLI generator; stdout is the artefact */

import { LEGAL_REFERENCES } from '../src/data/legal-references';

type LegalSourceType =
  | 'ley_organica'
  | 'reglamento'
  | 'ordenanza'
  | 'resolucion'
  | 'decreto'
  | 'normativa';
type LegalScope = 'nacional' | 'municipal' | 'institucional';

/** Escape a single SQL string literal using doubled single-quotes. */
function sql(value: string | null | undefined): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  return `'${value.replace(/'/g, "''")}'`;
}

const ALLOWED_SOURCE_TYPES: readonly LegalSourceType[] = [
  'ley_organica',
  'reglamento',
  'ordenanza',
  'resolucion',
  'decreto',
  'normativa',
];
const ALLOWED_SCOPES: readonly LegalScope[] = ['nacional', 'municipal', 'institucional'];

function assertSourceType(value: string, permitType: string, idx: number): LegalSourceType {
  if ((ALLOWED_SOURCE_TYPES as readonly string[]).includes(value)) {
    return value as LegalSourceType;
  }
  throw new Error(
    `Invalid source.type "${value}" in permit "${permitType}" (index ${idx}). Allowed: ${ALLOWED_SOURCE_TYPES.join(', ')}`,
  );
}

function assertScope(value: string, permitType: string, idx: number): LegalScope {
  if ((ALLOWED_SCOPES as readonly string[]).includes(value)) {
    return value as LegalScope;
  }
  throw new Error(
    `Invalid source.scope "${value}" in permit "${permitType}" (index ${idx}). Allowed: ${ALLOWED_SCOPES.join(', ')}`,
  );
}

function emitHeader(): void {
  console.log('-- Auto-generated by scripts/generate-legal-seed.ts');
  console.log('-- Source of truth: src/data/legal-references.ts');
  console.log('-- DO NOT EDIT BY HAND. Re-run the generator to update.');
  console.log('--');
  console.log('-- Seeds public.legal_references plus legal_sources, legal_consequences,');
  console.log('-- legal_required_documents and legal_process_steps.');
  console.log('');
  console.log('BEGIN;');
  console.log('');
  console.log('-- Idempotent: clean previous data');
  console.log('DELETE FROM public.legal_process_steps;');
  console.log('DELETE FROM public.legal_required_documents;');
  console.log('DELETE FROM public.legal_consequences;');
  console.log('DELETE FROM public.legal_sources;');
  console.log('DELETE FROM public.legal_references;');
  console.log('');
}

function emitFooter(): void {
  console.log('COMMIT;');
}

function emitPermit(permitType: string, ref: (typeof LEGAL_REFERENCES)[keyof typeof LEGAL_REFERENCES]): void {
  console.log(`-- ========== ${permitType} ==========`);

  // Parent row
  console.log(
    `INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)`,
  );
  console.log(
    `VALUES (${sql(permitType)}, ${sql(ref.description)}, ${sql(ref.frequencyBasis)}, ${sql(ref.estimatedCost ?? null)}, ${sql(ref.disclaimer ?? null)});`,
  );
  console.log('');

  // Sources
  ref.sources.forEach((source, idx) => {
    const type = assertSourceType(source.type, permitType, idx);
    const scope = assertScope(source.scope, permitType, idx);
    console.log(
      `INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)`,
    );
    console.log(
      `SELECT id, ${sql(source.name)}, ${sql(source.shortName)}, ${sql(type)}, ${sql(source.articles ?? null)}, ${sql(source.url ?? null)}, ${sql(source.entity)}, ${sql(scope)}, ${idx}`,
    );
    console.log(`FROM public.legal_references WHERE permit_type = ${sql(permitType)};`);
  });
  if (ref.sources.length > 0) console.log('');

  // Consequences
  ref.consequences.forEach((consequence, idx) => {
    console.log(
      `INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)`,
    );
    console.log(`SELECT id, ${sql(consequence)}, ${idx}`);
    console.log(`FROM public.legal_references WHERE permit_type = ${sql(permitType)};`);
  });
  if (ref.consequences.length > 0) console.log('');

  // Required documents
  ref.requiredDocuments.forEach((document, idx) => {
    console.log(
      `INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)`,
    );
    console.log(`SELECT id, ${sql(document)}, ${idx}`);
    console.log(`FROM public.legal_references WHERE permit_type = ${sql(permitType)};`);
  });
  if (ref.requiredDocuments.length > 0) console.log('');

  // Process steps
  ref.typicalProcess.forEach((step, idx) => {
    console.log(
      `INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)`,
    );
    console.log(`SELECT id, ${sql(step)}, ${idx}`);
    console.log(`FROM public.legal_references WHERE permit_type = ${sql(permitType)};`);
  });
  console.log('');
}

function main(): void {
  emitHeader();
  const permitTypes = Object.keys(LEGAL_REFERENCES) as Array<keyof typeof LEGAL_REFERENCES>;
  for (const permitType of permitTypes) {
    emitPermit(permitType, LEGAL_REFERENCES[permitType]);
  }
  emitFooter();
}

main();
