-- Auto-generated by scripts/generate-legal-seed.ts
-- Source of truth: src/data/legal-references.ts
-- DO NOT EDIT BY HAND. Re-run the generator to update.
--
-- Seeds public.legal_references plus legal_sources, legal_consequences,
-- legal_required_documents and legal_process_steps.

BEGIN;

-- Idempotent: clean previous data
DELETE FROM public.legal_process_steps;
DELETE FROM public.legal_required_documents;
DELETE FROM public.legal_consequences;
DELETE FROM public.legal_sources;
DELETE FROM public.legal_references;

-- ========== ruc ==========
INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)
VALUES ('ruc', 'El Registro Único de Contribuyentes (RUC) es el número de identificación tributaria para personas naturales y jurídicas en Ecuador. Es requisito previo para toda actividad económica formal y para la obtención de otros permisos.', 'El RUC se obtiene una sola vez, pero debe actualizarse dentro de 30 días ante cambios (nueva sucursal, cambio de actividad, dirección, etc.). Art. 9 Ley RUC establece la obligación de actualización. Cada establecimiento/sucursal debe registrarse como establecimiento adicional en el RUC.', 'Sin costo directo. Trámite gratuito en el SRI.', 'La información sobre el RUC es de aplicación nacional. Los plazos y multas específicas pueden variar según régimen tributario.');

INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ley del Registro Único de Contribuyentes', 'Ley RUC', 'ley_organica', 'Art. 1–3 (obligación de inscripción); Art. 9 (actualización de información)', 'https://www.sri.gob.ec', 'Servicio de Rentas Internas (SRI)', 'nacional', 0
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ley Orgánica del Régimen Tributario Interno (LORTI)', 'LORTI', 'ley_organica', 'Art. 96 (deberes formales del contribuyente)', 'https://www.sri.gob.ec/web/guest/lorti', 'Servicio de Rentas Internas (SRI)', 'nacional', 1
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Reglamento para la Aplicación de la Ley del RUC', 'Reglamento RUC', 'reglamento', 'Art. 4 (plazo de inscripción: 30 días); Art. 14 (establecimientos)', 'https://www.sri.gob.ec', 'Servicio de Rentas Internas (SRI)', 'nacional', 2
FROM public.legal_references WHERE permit_type = 'ruc';

INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Multas tributarias por no inscripción o datos desactualizados (Art. 97 LORTI)', 0
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Imposibilidad de facturar legalmente', 1
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Bloqueo para obtener otros permisos municipales y sectoriales', 2
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Clausura del establecimiento por incumplimiento tributario', 3
FROM public.legal_references WHERE permit_type = 'ruc';

INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Cédula de identidad del representante legal', 0
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Certificado de votación vigente', 1
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Documento que acredite dirección del establecimiento (planilla de servicio básico)', 2
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Escritura de constitución (personas jurídicas)', 3
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Nombramiento del representante legal inscrito en el Registro Mercantil', 4
FROM public.legal_references WHERE permit_type = 'ruc';

INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Acceder al portal web del SRI o acudir a oficinas presenciales', 0
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Completar formulario de inscripción con datos de la empresa', 1
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Registrar cada establecimiento/sucursal como establecimiento adicional', 2
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Obtener certificado de RUC impreso', 3
FROM public.legal_references WHERE permit_type = 'ruc';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Solicitar autorización de comprobantes de venta', 4
FROM public.legal_references WHERE permit_type = 'ruc';

-- ========== patente_municipal ==========
INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)
VALUES ('patente_municipal', 'La patente municipal es un impuesto y permiso obligatorio para ejercer actividades económicas dentro de un cantón. En Quito, es administrada por el Municipio del Distrito Metropolitano de Quito (MDMQ) y debe renovarse anualmente.', 'Renovación anual. Art. 547 del COOTAD establece el impuesto de patente como anual, calculado sobre el patrimonio del contribuyente. En Quito, se integra dentro de la LUAE (Ordenanza 308). El período fiscal generalmente va de enero a diciembre, con plazo de pago hasta marzo.', 'Variable según patrimonio del contribuyente. Rango típico para restaurantes: $50–$500 USD/año. Art. 548 COOTAD establece tarifa entre $10 y $25,000.', 'Las ordenanzas municipales varían por cantón. Los valores y procesos descritos aplican principalmente a Quito. Validar con el GAD correspondiente en otras ciudades.');

INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Código Orgánico de Organización Territorial, Autonomía y Descentralización (COOTAD)', 'COOTAD', 'ley_organica', 'Art. 546–551 (impuesto de patentes municipales: base imponible, tarifas, obligación de pago)', 'https://www.finanzas.gob.ec/wp-content/uploads/downloads/2012/09/CODIGO_ORGANIZACION_TERRITORIAL.pdf', 'Gobiernos Autónomos Descentralizados (GAD)', 'nacional', 0
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ordenanza Metropolitana de Quito — Licencia Metropolitana Única de Actividades Económicas (LUAE)', 'Ordenanza LUAE Quito', 'ordenanza', 'Ordenanza No. 308 (integra patente, turismo, publicidad exterior, bomberos en un solo trámite)', 'https://www.quito.gob.ec', 'Municipio del Distrito Metropolitano de Quito', 'municipal', 1
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Código Orgánico Tributario', 'COT', 'ley_organica', 'Art. 21 (intereses por mora); Art. 323–327 (sanciones por incumplimiento)', 'https://www.sri.gob.ec', 'Estado ecuatoriano', 'nacional', 2
FROM public.legal_references WHERE permit_type = 'patente_municipal';

INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Multas e intereses por mora (Art. 21 Código Tributario)', 0
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Imposibilidad de renovar otros permisos operativos', 1
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Clausura del establecimiento por parte de la Agencia Metropolitana de Control', 2
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Bloqueo para obtener la LUAE (en Quito, la patente es componente de la LUAE)', 3
FROM public.legal_references WHERE permit_type = 'patente_municipal';

INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'RUC actualizado', 0
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Formulario de solicitud LUAE (en Quito)', 1
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Declaración de impuesto a la renta del año anterior', 2
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Copia de cédula del representante legal', 3
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Certificado de uso de suelo compatible (si es primera vez)', 4
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Permiso de bomberos vigente', 5
FROM public.legal_references WHERE permit_type = 'patente_municipal';

INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Verificar uso de suelo compatible para la dirección del local', 0
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Acceder al portal de trámites del municipio (en Quito: tramites.quito.gob.ec)', 1
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Llenar solicitud de LUAE o patente municipal', 2
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Adjuntar documentación requerida', 3
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Pagar la tasa correspondiente según patrimonio', 4
FROM public.legal_references WHERE permit_type = 'patente_municipal';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Esperar emisión de la licencia/patente', 5
FROM public.legal_references WHERE permit_type = 'patente_municipal';

-- ========== bomberos ==========
INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)
VALUES ('bomberos', 'El permiso de funcionamiento del Cuerpo de Bomberos certifica que un establecimiento cumple con normas de seguridad contra incendios, incluyendo extintores, señalización, salidas de emergencia y sistemas de detección.', 'Renovación anual. Art. 35 de la Ley de Defensa Contra Incendios establece que todo establecimiento debe contar con inspección anual. En la práctica, el permiso de bomberos se renueva cada año calendario. En Quito, se integra dentro de la LUAE.', 'Variable por jurisdicción y tamaño del local. En Quito: $20–$100 USD para locales de riesgo bajo/moderado (restaurantes típicos). Locales grandes o con riesgo alto: $100–$500 USD.', 'Los procedimientos, tasas y categorías de riesgo varían significativamente por jurisdicción (Cuerpo de Bomberos local). En Quito el trámite se integra en la LUAE. Validar siempre con el cuerpo de bomberos correspondiente.');

INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ley de Defensa Contra Incendios', 'Ley de Defensa Contra Incendios', 'ley_organica', 'Art. 35 (inspección obligatoria); Art. 40 (tasas por servicios); Art. 41 (sanciones)', 'https://www.gob.ec/regulaciones/ley-defensa-contra-incendios', 'Cuerpo de Bomberos (jurisdiccional)', 'nacional', 0
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Reglamento de Prevención, Mitigación y Protección Contra Incendios', 'Reglamento Contra Incendios', 'reglamento', 'Art. 350 (permisos de funcionamiento); Art. 351 (requisitos por categoría de riesgo); Art. 352 (inspecciones)', 'https://www.gob.ec/ccbbch/tramites/permiso-funcionamiento', 'Ministerio de Inclusión Económica y Social / Bomberos', 'nacional', 1
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Norma INEN NTE 439 — Señalización de seguridad', 'NTE INEN 439', 'normativa', 'Norma completa (señalización, colores, pictogramas de seguridad)', 'https://www.normalizacion.gob.ec', 'Servicio Ecuatoriano de Normalización (INEN)', 'nacional', 2
FROM public.legal_references WHERE permit_type = 'bomberos';

INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Clausura temporal o definitiva del establecimiento (Art. 41 Ley de Defensa Contra Incendios)', 0
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Multas que van desde 1 a 20 salarios básicos según la infracción', 1
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Responsabilidad civil y penal en caso de siniestro sin permiso vigente', 2
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Imposibilidad de renovar la LUAE o patente municipal', 3
FROM public.legal_references WHERE permit_type = 'bomberos';

INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Solicitud de inspección dirigida al Cuerpo de Bomberos', 0
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'RUC del establecimiento', 1
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Copia de cédula del representante legal', 2
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Plano del local con ubicación de extintores y salidas de emergencia', 3
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Certificado de mantenimiento de extintores vigente', 4
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Comprobante de pago de tasa de inspección', 5
FROM public.legal_references WHERE permit_type = 'bomberos';

INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Solicitar inspección al Cuerpo de Bomberos de la jurisdicción', 0
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Pagar tasa de inspección (varía según metros cuadrados y categoría)', 1
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Recibir la visita del inspector de bomberos', 2
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Cumplir observaciones si las hubiera (plazo habitual: 15–30 días)', 3
FROM public.legal_references WHERE permit_type = 'bomberos';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Recibir el certificado/permiso de funcionamiento', 4
FROM public.legal_references WHERE permit_type = 'bomberos';

-- ========== arcsa ==========
INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)
VALUES ('arcsa', 'El permiso de funcionamiento de la Agencia Nacional de Regulación, Control y Vigilancia Sanitaria (ARCSA) es obligatorio para establecimientos que manejan alimentos, bebidas, productos de higiene, cosméticos o medicamentos. Autoriza la operación bajo control sanitario.', 'Renovación anual. Art. 8 del Reglamento Sustitutivo establece vigencia de un año desde la fecha de emisión. La solicitud de renovación debe realizarse al menos 30 días antes del vencimiento. El trámite se realiza en línea a través del portal de ARCSA.', 'Según categoría de riesgo: Riesgo bajo (Tipo C): ~$65.10 USD. Riesgo medio (Tipo B): ~$171.64 USD. Riesgo alto (Tipo A): ~$385.44 USD. Restaurantes típicos: Tipo B o C.', 'Las categorías y costos de ARCSA se actualizan periódicamente. El portal oficial de ARCSA es la fuente más actualizada para tasas y clasificaciones.');

INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ley Orgánica de Salud', 'Ley Orgánica de Salud', 'ley_organica', 'Art. 129 (control sanitario de establecimientos); Art. 130 (autorización de funcionamiento); Art. 131 (cumplimiento de normas sanitarias)', 'https://wipolex.wipo.int/es/legislation/details/18941', 'Ministerio de Salud Pública / ARCSA', 'nacional', 0
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Reglamento Sustitutivo para Otorgar Permisos de Funcionamiento a Establecimientos Sujetos a Vigilancia y Control Sanitario', 'Reglamento ARCSA Permisos', 'reglamento', 'Art. 4 (clasificación de establecimientos); Art. 5 (requisitos); Art. 8 (vigencia y renovación); Art. 10 (inspecciones)', 'https://www.controlsanitario.gob.ec/wp-content/uploads/downloads/2015/04/A-4712-Reglamento-para-otorgar-Permisos-de-funcionamiento-de-Establecimientos.pdf', 'ARCSA', 'nacional', 1
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Resolución ARCSA-DE-067-2015-GGG — Normativa técnica sanitaria para restaurantes y servicios afines', 'Resolución ARCSA 067-2015', 'resolucion', 'Capítulo II (condiciones del establecimiento); Capítulo III (manipulación de alimentos); Capítulo IV (almacenamiento)', 'https://permisosfuncionamiento.controlsanitario.gob.ec/', 'ARCSA', 'nacional', 2
FROM public.legal_references WHERE permit_type = 'arcsa';

INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Clausura inmediata del establecimiento (Art. 131 Ley Orgánica de Salud)', 0
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Multas de 1 a 10 salarios básicos unificados', 1
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Decomiso de productos en caso de riesgo sanitario', 2
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Responsabilidad penal si se generan daños a la salud pública', 3
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Prohibición de operar hasta obtener el permiso', 4
FROM public.legal_references WHERE permit_type = 'arcsa';

INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'RUC del establecimiento', 0
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Cédula y certificado de votación del representante legal', 1
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Categorización del establecimiento (según clasificación ARCSA)', 2
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Plano del establecimiento con distribución de áreas', 3
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Certificados de salud del personal que manipula alimentos', 4
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Programa de control de plagas', 5
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Certificado de capacitación en manipulación de alimentos', 6
FROM public.legal_references WHERE permit_type = 'arcsa';

INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Registrarse en el portal de ARCSA (permisosfuncionamiento.controlsanitario.gob.ec)', 0
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Seleccionar categoría del establecimiento', 1
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Cargar documentación requerida', 2
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Pagar tasa correspondiente en línea', 3
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Esperar revisión documental (y posible inspección para categorías de riesgo alto)', 4
FROM public.legal_references WHERE permit_type = 'arcsa';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Descargar permiso de funcionamiento digital', 5
FROM public.legal_references WHERE permit_type = 'arcsa';

-- ========== uso_suelo ==========
INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)
VALUES ('uso_suelo', 'El Informe de Compatibilidad de Uso de Suelo (ICUS) verifica que la actividad económica que se desea realizar es compatible con la zonificación del predio. Es prerequisito para obtener la patente municipal y la LUAE.', 'Trámite por evento: se obtiene al abrir un nuevo establecimiento o al cambiar de actividad económica. No tiene vencimiento fijo, pero puede requerirse nuevamente si cambia la normativa de zonificación o el uso del suelo del sector. En algunos cantones se solicita renovación periódica.', 'Variable por municipio. En Quito: ~$5–$30 USD por trámite.', 'La zonificación varía drásticamente entre barrios y cantones. Un uso compatible en La Mariscal puede no serlo en La Floresta. Siempre consultar el PUOS vigente del municipio.');

INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Código Orgánico de Organización Territorial, Autonomía y Descentralización (COOTAD)', 'COOTAD', 'ley_organica', 'Art. 54 literal c) (competencia de GAD en uso de suelo); Art. 466 (planes de ordenamiento territorial)', 'https://www.finanzas.gob.ec/wp-content/uploads/downloads/2012/09/CODIGO_ORGANIZACION_TERRITORIAL.pdf', 'Gobiernos Autónomos Descentralizados (GAD)', 'nacional', 0
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ley Orgánica de Ordenamiento Territorial, Uso y Gestión de Suelo (LOOTUGS)', 'LOOTUGS', 'ley_organica', 'Art. 73 (clasificación del suelo); Art. 91 (uso del suelo); Art. 92 (compatibilidad de uso)', 'https://www.habitatyvivienda.gob.ec', 'Ministerio de Desarrollo Urbano y Vivienda', 'nacional', 1
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Plan de Uso y Ocupación del Suelo (PUOS) — Quito', 'PUOS Quito', 'ordenanza', 'Mapa de zonificación y tabla de compatibilidades por zona', 'https://www.quito.gob.ec', 'Municipio del Distrito Metropolitano de Quito', 'municipal', 2
FROM public.legal_references WHERE permit_type = 'uso_suelo';

INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Negación de la LUAE o patente municipal', 0
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Clausura del establecimiento por operación en zona no compatible', 1
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Multas municipales por uso irregular del suelo', 2
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Obligación de reubicar el negocio', 3
FROM public.legal_references WHERE permit_type = 'uso_suelo';

INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Solicitud dirigida a la Administración Zonal correspondiente', 0
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Copia del RUC', 1
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Copia de la escritura del inmueble o contrato de arrendamiento', 2
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Croquis de ubicación del predio', 3
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Cédula del propietario del inmueble y del solicitante', 4
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Pago de predio actualizado (impuesto predial)', 5
FROM public.legal_references WHERE permit_type = 'uso_suelo';

INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Consultar zonificación del predio en el PUOS (disponible en línea para Quito)', 0
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Solicitar el ICUS en la Administración Zonal correspondiente', 1
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Presentar documentación del inmueble y la actividad planificada', 2
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Esperar resolución (plazo habitual: 5–15 días hábiles)', 3
FROM public.legal_references WHERE permit_type = 'uso_suelo';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Recibir informe de compatibilidad favorable o desfavorable', 4
FROM public.legal_references WHERE permit_type = 'uso_suelo';

-- ========== rotulacion ==========
INSERT INTO public.legal_references (permit_type, description, frequency_basis, estimated_cost, disclaimer)
VALUES ('rotulacion', 'El permiso de publicidad exterior o rotulación autoriza la instalación de rótulos, letreros, toldos y cualquier elemento de publicidad visible desde el espacio público. En Quito se gestiona como componente de la LUAE.', 'Trámite por evento: se solicita al instalar o modificar rotulación. No tiene vencimiento anual fijo, aunque en Quito se renueva como componente de la LUAE. Modificaciones de diseño, tamaño o ubicación requieren nueva autorización.', 'En Quito: variable según metros cuadrados de publicidad. Rango típico para restaurantes: $20–$150 USD.', 'Las normas de publicidad exterior varían significativamente entre municipios. En zonas patrimoniales (Centro Histórico de Quito, por ejemplo) aplican restricciones adicionales.');

INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ordenanza Metropolitana de Publicidad Exterior — Quito', 'Ordenanza Publicidad Exterior', 'ordenanza', 'Art. 4 (autorización obligatoria); Art. 8 (dimensiones y especificaciones); Art. 15 (sanciones)', 'https://www.quito.gob.ec', 'Municipio del Distrito Metropolitano de Quito', 'municipal', 0
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'Ordenanza LUAE — Quito (No. 308)', 'Ordenanza LUAE', 'ordenanza', 'Integra el componente de publicidad exterior dentro de la LUAE', 'https://www.quito.gob.ec', 'Municipio del Distrito Metropolitano de Quito', 'municipal', 1
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_sources (legal_reference_id, name, short_name, type, articles, url, entity, scope, display_order)
SELECT id, 'COOTAD — Competencias municipales', 'COOTAD', 'ley_organica', 'Art. 54 literal o) (regulación de publicidad en el espacio público)', 'https://www.finanzas.gob.ec/wp-content/uploads/downloads/2012/09/CODIGO_ORGANIZACION_TERRITORIAL.pdf', 'Estado ecuatoriano', 'nacional', 2
FROM public.legal_references WHERE permit_type = 'rotulacion';

INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Retiro forzoso del rótulo o publicidad por la autoridad municipal', 0
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Multas que varían según el tamaño y tipo de infracción', 1
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_consequences (legal_reference_id, consequence, display_order)
SELECT id, 'Imposibilidad de incluir el componente de publicidad en la LUAE', 2
FROM public.legal_references WHERE permit_type = 'rotulacion';

INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Solicitud de autorización de publicidad exterior', 0
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Diseño gráfico del rótulo con dimensiones exactas', 1
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Fotografía de la fachada actual', 2
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Croquis de ubicación del rótulo', 3
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_required_documents (legal_reference_id, document, display_order)
SELECT id, 'Autorización del propietario del inmueble (si es arrendado)', 4
FROM public.legal_references WHERE permit_type = 'rotulacion';

INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Preparar diseño del rótulo según especificaciones municipales', 0
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Incluir el componente de publicidad exterior en la solicitud LUAE (Quito)', 1
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Presentar documentación gráfica y técnica', 2
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Esperar aprobación de la Administración Zonal', 3
FROM public.legal_references WHERE permit_type = 'rotulacion';
INSERT INTO public.legal_process_steps (legal_reference_id, step, display_order)
SELECT id, 'Instalar el rótulo según el diseño aprobado', 4
FROM public.legal_references WHERE permit_type = 'rotulacion';

COMMIT;
